apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
  labels:
    app: backup
spec:
  schedule: "*/2 * * * *"  # Runs every day at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: busybox
            command: ["/bin/sh", "-c"]
            args:
              - tar czf /backup/backup-$(date +%Y%m%d%H%M%S).tar.gz /data && echo "Backup complete"
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
            - name: data-volume
              mountPath: /data
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: local-pvc-backup
          - name: data-volume
            persistentVolumeClaim:
              claimName: local-pvc
          affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - my-kind-cluster-worker2
                  - my-kind-cluster-worker

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Ek node par sirf ek pod access kar sakta hai
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/mnt/disks/vol1"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "my-kind-cluster-worker2"
                - "my-kind-cluster-worker" # Ye volume sirf is node par available hoga

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi  # 10 Megabytes request
  storageClassName: local-storage


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv1
spec:
  capacity:
    storage: 20Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Ek node par sirf ek pod access kar sakta hai
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/mnt/disks/vol1"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "my-kind-cluster-worker2"
                - "my-kind-cluster-worker"  # Ye volume sirf is node par available hoga


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi  # 10 Megabytes request
  storageClassName: local-storage
