apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job
  labels:
    app: backup
spec:
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: backup
    spec:
      restartPolicy: OnFailure
      containers:
      - name: backup
        image: busybox
        command: ["sh", "-c", "tar czf /backup/backup-$(date +%Y%m%d%H%M%S).tar.gz /data && echo 'Backup complete'"]
        volumeMounts:
        - name : pod-volume
          mountPath: /data
        - name: backup-volume
          mountPath: /backup
      volumes:
      - name: backup-volume
        hostPath:
          path: /tmp/backup
          type: DirectoryOrCreate
      - name : pod-volume
        hostPath:
          path: /mnt/data
          type: DirectoryOrCreate



