kind: Job
apiVersion: batch/v1
metadata:
    name: demo-job
    namespace: nginx
spec:
  completions: 5
  parallelism: 4
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec: 
        containers:
        - name: batch-container
          image: busybox:latest
          command: ["sh","-c","echo hello india && sleep 20"]
      
        restartPolicy: Never
